name: Orebfuscator
main: lishid.orebfuscator.Orebfuscator
version: 1.3.6
author: lishid
softdepend: [Spout, ChunkScrambler]
load: startup
description: >
             This plugin obfuscates chunk packets that is sent to players to prevent x-ray.
commands:
  ofc:
    description: Manage Orebfuscator.
    usage: |
           /<command> engine <1/2> - Set engine mode to 1 or 2
           /<command> initialradius [number] - Set block initial radius
           /<command> updateradius [number] - Set block update radius
           /<command> threads [number] - Set allowed processing threads
           /<command> <enable/disable> - Change the state of the plugin
           /<command> <enable/disable> <updatebreak|updatedamage>
           /<command> <enable/disable> <updatephysics|updateexplosion>
           /<command> <enable/disable> <darknesshide> - DarknessObfuscate
           /<command> <enable/disable> <op|perms> - OPs/Permissions
           /<command> <enable/disable> updatethread - Toggle update thread
           /<command> <enable/disable> cache - Chunk caching
           /<command> <enable/disable> verbose - Verbose mode
           /<command> <enable/disable> world <worldname>
           /<command> reload - Reload from config file
           /<command> status - Show status of Orebfuscator
           /<command> clearcache - Clear all cache
  chunk:
    description: Re-send chunks.
    usage: |
           /<command> [radius=2] Send the chunks within a specific radius